### ISSUE TITLE
Production launch checklist

### ISSUE THREAD

**Issue by coffeejunk** [sharkipedia/sharkipedia#14]
- [x] setup DNS, and host in `production.rb`
- [x] setup Email Account
- [x] setup S3 account for file uploads
- [x] setup CDN for asset delivery
